### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by frafra** [alexbruy/processing-saga#1]
Hi,
it would be nice to write few words in README.md about how to install the plugin.

Thanks!

**Comment by alexbruy** [comment]
Closing as won'tfix. QGIS documentation already covers plugins management.

**Comment by frafra** [comment]
Not even a couple of links then?

QGIS documentations shows how to use QGIS to install plugins, not how to install your plugins from a GitHub repository, especially because there is no single way. Your plugin is not available on https://plugins.qgis.org/ so I really do not understand how to install or improve yours. QGIS still need a properly done zip file. Downloading the zip file of this project does not make it work on QGIS. `make` does nothing, because `ts` is the first target and the `PRO_FILES` list is empty, as there are no *.pro files (and those targets are not flagged as PHONY even). It does not seem trivial to use this plugin or to develop it, nor I found any resource to make it work.

**Comment by alexbruy** [comment]
GitHub repository contains **sources**, not ready-to-use plugin. These sources are not for users. Well, not for all users, maybe advanced users can make use of them but honestly I still don't see any point in this. For users there is a **repository** with packages.

**Comment by frafra** [comment]
> Installation
> Plugin published in my repository.

That is a quote from your website, from the page linked in the GitHub description: https://plugins.bruy.me/processing-saga.html. You tell the user to come here to find information about how to install the plugin actually.

GitHub repositories contains whatever you want to, as there is there releases pages too nowadays, and for many Python repositories there is no clear distinction, as there is no compilation involved, but that is not the point. The problem is that:
- As user I have no idea how to find a ready to use version of your plugin when I land on the GitHub page and it is not published on the QGIS plugins repository
- As developer I have no idea how to use your code on my QGIS to do improvements, as there is no documentation nor link: I only see a broken `Makefile`.
- As maintainer I have no idea about how to package your code (see previous point).

Of course you are free to keep things as they are now. Mine is just a suggestion in order to help people use your code.

**Comment by Joshua-IRT** [comment]
For future readers who find the lack of documentation (and even any pointers from the developer), here's how to get it working:

1. In QGIS, open the Plugins Manager and go to settings. Add a new repository using the developer's link:  https://plugins.bruy.me/plugins/plugins.xml
2. Because this plugin is currently flagged as experiment, you need to check the box on the settings tab to show experiment plugins.
3. The "SAGA for Processing" plugin should now be available in "All" tab.
