### ISSUE TITLE
processing-saga in not working/available

### ISSUE THREAD

**Issue by skampus** [alexbruy/processing-saga#2]
hi alexander, I'd like to use your processing-saga plugin but in your repository [1] it seems it is not available.
Also if I try to install it on QGIS LTR by downloading the .zip package from your git page [2], it returns this error:
"ModuleNotFoundError: No module named 'processing_saga' ".

Can you help me, please?

thank you in advance

stefano

[1] https://plugins.bruy.me/plugins/plugins.xml
[2] https://github.com/alexbruy/processing-saga

**Comment by alexbruy** [comment]
Invalid. Plugin available via repository and works.

Please check QGIS documentation to learn how to use and manage plugins.

**Comment by skampus** [comment]
Sorry, but I have added your repo to plugin list but SAGA plugin is not available, as you can see in the screenshot

[1] https://plugins.bruy.me/plugins/plugins.xml

![bruy_qgis_repo](https://user-images.githubusercontent.com/4558522/67189879-50cf3180-f3ef-11e9-9b9d-17206c197a4b.png)

**Comment by skampus** [comment]
Thanks a lot. It was my mistake: I did not read that plugin is available from QGIS > 3.9.

thank you again

stefano
