### ISSUE TITLE
Path option not visible QGIS 3.10

### ISSUE THREAD

**Issue by yomegui65** [alexbruy/processing-saga#4]
Hi, 

I'm a beginner on QGIS, doing an online course. I have to use SAGA modules. I've struggling for 2 days to be able to use them, but i got an error for each operation I try (kiging, B-Spline etc...) It seems that Qgis doesn't find the saga file.

I have found on different topics the QGIS options (from menu "Settings → Options" and go to the "Processing" tab) but I do not have this path option !

I found so the plugin SAGA processing then I thought that would save me ! But... Still no options. Not as on your home page. Here's what I got :
![image](https://user-images.githubusercontent.com/63556375/79076053-5ac75280-7cf7-11ea-8a0b-56002cd4b944.png)

I've installed QGIS with the standalone installer. An old version of SAGA was already there (C:\Program Files\QGIS 3.10\apps\saga-ltr) once QGIS was installed. I've downloaded the last version and placed the portable program folder in C:\Program Files\QGIS 3.10\apps\saga-7.6.2.

Is this issue known ? Did I do something wrong ?

Thank you

**Comment by alexbruy** [comment]
Please describe bug with more details, I hardly understand what is wrong. Also not that this repository is for a 3rd party plugin, I'm not responsible for any bugs in QGIS core provider.

**Comment by jonnyforestGIS** [comment]
@yomegui65 just test. You need to download the saga binaries and point in the processing provider the path to binaries of the SAGA GIS.

Go here: https://sourceforge.net/projects/saga-gis/files/SAGA%20-%207/SAGA%20-%207.6.0/saga-7.6.0_x64.zip/download

Extract the binaries to a folder then:
In Menu Processing in the providers double click in saga path on saga path and put the directory of SAGA.

That's it.

It's working on mine.

@alexbruy this is not a bug.
Cheers.
