### ISSUE TITLE
How to install this Plugin? What to download?

### ISSUE THREAD

**Issue by FelixTheAwesomeCat** [alexbruy/processing-saga#5]
Is there any documentation how to install your plugin? I would love to get rid of SAGA 2...

**Comment by alexbruy** [comment]
Please read QGIS documentation.

**Comment by FelixTheAwesomeCat** [comment]
I already did, but I couldn't find any information about installing third party processing providers. Am I missing something? On your website under "Installation" you kinda skipped the installation process?

> Once installed and enabled, SAGA for Processing is registered as a Processing provider.

So how do u actually install and enable it? Could you give me a hint where exactly I have to look in the documentation? 
I found this about installing plugins:

> https://docs.qgis.org/3.10/en/docs/user_manual/plugins/plugins.html#the-install-from-zip-tab

However for the installation I would need a .zip file. I am kinda lost.

**Comment by Joshua-IRT** [comment]
There is definitely an issue trying to install this.

I downloaded the repo as a ZIP and encountered the same error as @FelixTheAwesomeCat.

I then renamed the folder within the zip from `processing-saga-master` to `processing_saga` based on the error message provided. This gets further, but now reports another file is missing:

```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users/[username]/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\processing_saga\\iosettings.txt' 
Traceback (most recent call last):
  File "C:\Users/[username]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_saga\sagaProvider.py", line 66, in load
    with open(os.path.join(pluginPath, "iosettings.txt")) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users/[username]/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins\\processing_saga\\iosettings.txt'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.0-Odense Odense, decaadbb31 

Python Path:
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python
C:/Users/[username]/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/[username]/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.0\bin\python39.zip
C:\PROGRA~1\QGIS32~1.0\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib
C:\Program Files\QGIS 3.20.0\bin
C:\Users\[username]\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.0\apps\Python39\lib\site-packages\Pythonwin
C:/Users/[username]/AppData/Roaming/QGIS/QGIS3\profiles\default/python
D:/Data/Projects/QR/Shapefiles
```
